# Generated by Django 5.2.1 on 2025-06-03 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pcbuilder', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pcbuild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_builds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pcbuildcomponent',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pcbuilder.pcbuild'),
        ),
        migrations.AddField(
            model_name='pcbuildcomponent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AddField(
            model_name='pcbuildcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='prebuiltpc',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prebuilt_pcs', to='pcbuilder.categorypc'),
        ),
        migrations.AddField(
            model_name='prebuiltpccomponent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
        migrations.AddField(
            model_name='prebuiltpccomponent',
            name='prebuilt_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pcbuilder.prebuiltpc'),
        ),
        migrations.AddField(
            model_name='prebuiltpccomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='savedpcbuild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pc_builds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pcbuildcomponent',
            unique_together={('build', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='prebuiltpccomponent',
            unique_together={('prebuilt_pc', 'category')},
        ),
    ]
