# Generated by Django 5.2 on 2025-06-20 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0002_initial'),
        ('store', '0008_remove_userpromocode_email_promocode_is_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorypc',
            options={'verbose_name': 'Категория готового ПК', 'verbose_name_plural': 'Категории готовых ПК'},
        ),
        migrations.AlterModelOptions(
            name='compatibilityrule',
            options={'verbose_name': 'Правило совместимости', 'verbose_name_plural': 'Правила совместимости'},
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['price'], 'verbose_name': 'Готовый компьютер (упрощенный)', 'verbose_name_plural': 'Готовые компьютеры (упрощенные)'},
        ),
        migrations.AlterModelOptions(
            name='pcbuild',
            options={'verbose_name': 'Сборка ПК пользователя', 'verbose_name_plural': 'Сборки ПК пользователей'},
        ),
        migrations.AlterModelOptions(
            name='pcbuildcomponent',
            options={'verbose_name': 'Компонент в сборке', 'verbose_name_plural': 'Компоненты в сборках'},
        ),
        migrations.AlterModelOptions(
            name='savedpcbuild',
            options={'verbose_name': 'Сохраненная сборка', 'verbose_name_plural': 'Сохраненные сборки'},
        ),
        migrations.AlterField(
            model_name='categorypc',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='categorypc',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='categorypc',
            name='icon',
            field=models.CharField(max_length=50, verbose_name='Иконка (CSS класс)'),
        ),
        migrations.AlterField(
            model_name='categorypc',
            name='name',
            field=models.CharField(choices=[('gaming', 'Для игр'), ('work', 'Для работы'), ('office', 'Для офиса'), ('design', 'Для дизайна'), ('study', 'Для учебы'), ('streaming', 'Для стриминга')], max_length=50, unique=True, verbose_name='Системное имя'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='category1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_1', to='store.category', verbose_name='Категория 1'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='category2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_2', to='store.category', verbose_name='Категория 2'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='error_message',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сообщение об ошибке'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='operator',
            field=models.CharField(blank=True, choices=[('=', 'Равно'), ('!=', 'Не равно'), ('<', 'Меньше'), ('<=', 'Меньше или равно'), ('>', 'Больше'), ('>=', 'Больше или равно')], max_length=2, verbose_name='Оператор'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='spec1',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_1', to='store.specification', verbose_name='Характеристика 1'),
        ),
        migrations.AlterField(
            model_name='compatibilityrule',
            name='spec2',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compat_rules_2', to='store.specification', verbose_name='Характеристика 2'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='pcbuilder.categorypc', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='graphics_card',
            field=models.CharField(max_length=100, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='level',
            field=models.CharField(choices=[('start', 'Начальный уровень'), ('pro', 'Оптимальный выбор'), ('ultra', 'Максимальная мощность')], max_length=10, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='level_color',
            field=models.CharField(default='blue-500', max_length=20, verbose_name='Цвет уровня'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(max_length=100, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(max_length=50, verbose_name='Оперативная память'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='storage',
            field=models.CharField(max_length=50, verbose_name='Накопитель'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='pcbuild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pc_builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='pcbuildcomponent',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pcbuilder.pcbuild', verbose_name='Сборка'),
        ),
        migrations.AlterField(
            model_name='pcbuildcomponent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pcbuildcomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='pcbuildcomponent',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='prebuiltpc',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prebuilt_pcs', to='pcbuilder.categorypc', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='prebuiltpc',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='prebuiltpc',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='prebuiltpccomponent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='prebuiltpccomponent',
            name='prebuilt_pc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pcbuilder.prebuiltpc', verbose_name='Готовая сборка'),
        ),
        migrations.AlterField(
            model_name='prebuiltpccomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='savedpcbuild',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения'),
        ),
        migrations.AlterField(
            model_name='savedpcbuild',
            name='data',
            field=models.JSONField(verbose_name='Данные сборки'),
        ),
        migrations.AlterField(
            model_name='savedpcbuild',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название сборки'),
        ),
        migrations.AlterField(
            model_name='savedpcbuild',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='savedpcbuild',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_pc_builds', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
