# Generated by Django 5.2 on 2025-06-22 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcbuilder', '0004_alter_compatibilityrule_category1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
