# Generated by Django 5.2.1 on 2025-06-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_min_stock_product_stock_promocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_lines/', verbose_name='Изображение'),
        ),
    ]
