# Generated by Django 5.2.1 on 2025-06-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Отметьте, если товар является популярным и должен отображаться в специальных блоках.', verbose_name='Популярный товар'),
        ),
    ]
