# Generated by Django 5.2 on 2025-06-20 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_is_popular'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='is_personal',
            field=models.BooleanField(default=False, verbose_name='Персональный'),
        ),
        migrations.AddField(
            model_name='userpromocode',
            name='is_personal',
            field=models.BooleanField(default=False, verbose_name='Персональный'),
        ),
        migrations.AlterField(
            model_name='userpromocode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_promocodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
