# Generated by Django 5.2 on 2025-06-20 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_userpromocode_is_personal_userpromocode_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpromocode',
            name='email',
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_email',
            field=models.BooleanField(default=False, help_text='Если выбран, промокод не показывается никому, но может быть использован для рассылки', verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='is_personal',
            field=models.BooleanField(default=False, help_text='Если выбран, промокод не показывается никому, пока не назначен пользователям', verbose_name='Персональный'),
        ),
        migrations.AlterField(
            model_name='userpromocode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_promocodes', to=settings.AUTH_USER_MODEL),
        ),
    ]
