# Generated by Django 5.2 on 2025-06-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_userpromocode_email_promocode_is_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
    ]
