# Generated by Django 5.2 on 2025-06-22 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_product_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspec',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='store.product', verbose_name='Товар'),
        ),
    ]
