# Generated by Django 5.2 on 2025-06-22 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_productspec_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='store.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='promocodeusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userpromocode',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Кто назначил промокод', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Кто назначает'),
        ),
        migrations.AlterField(
            model_name='userpromocode',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promocode', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='userpromocode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_promocodes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
