# Generated by Django 5.2 on 2025-06-22 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.productline', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='specification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.specification', verbose_name='Характеристика'),
        ),
    ]
