# Generated by Django 5.2 on 2025-06-22 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
