# Generated by Django 5.2.1 on 2025-06-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('star', 'Звезда'), ('shield', 'Щит'), ('support', 'Поддержка'), ('rocket', 'Ракета'), ('gift', 'Подарок'), ('heart', 'Сердце')], default='star', max_length=20, verbose_name='Иконка')),
                ('color', models.CharField(default='#7a85ff', max_length=20, verbose_name='Цвет иконки (hex)')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/', verbose_name='Картинка')),
                ('button1_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки 1')),
                ('button1_url', models.URLField(blank=True, verbose_name='Ссылка кнопки 1')),
                ('button2_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки 2')),
                ('button2_url', models.URLField(blank=True, verbose_name='Ссылка кнопки 2')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Слайд карусели',
                'verbose_name_plural': 'Слайды карусели',
                'ordering': ['order'],
            },
        ),
    ]
