# Generated by Django 5.2 on 2025-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactinfo_alter_heroslide_options_and_more'),

  ]

    operations = [
        migrations.RemoveField(
            model_name='heroslide',
            name='link',
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button1_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button1_url',
            field=models.URLField(blank=True, verbose_name='URL кнопки 1'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button2_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки 2'),
        ),
        migrations.AddField(
            model_name='heroslide',
            name='button2_url',
            field=models.URLField(blank=True, verbose_name='URL кнопки 2'),
        ),
    ]
