# Generated by Django 5.2.1 on 2025-06-04 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('store', '0002_product_min_stock_product_stock_promocode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promocode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_promocode', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Промокод в корзине',
                'verbose_name_plural': 'Промокоды в корзине',
            },
        ),
    ]
